WIP: Dev 2.0 observable tests
arturkulig/immview pull request #1
Opened 2017-01-04 22:12 UTC by sebryu

2017-01-04 23:44 UTC, arturkulig requested changes
Ogólnie spoko - tyćkie zmiany. Dzięki! Strasznie się cieszę, że to czytam!

2017-01-04 23:44 UTC, arturkulig commented on src/Observable.spec.ts
> +        const tester = value => {
[optional] Nie ma potrzeby robić z tego funkcji. Treść funkcji może być w miejscu jej użycia.

2017-01-04 23:44 UTC, arturkulig commented on src/Observable.spec.ts
> +            setTimeout(done)
[hint]

Tak tylko, żeby wyjaśnić.
setTimeout(done) jest po to, bo done od razu, w miejscu wywołania uruchamia następny test.
Normalnie to nie problem - Jasmine przełącza kontekst na inny test i wszystko śmiga.
Tutaj jest problem, bo będąc w callbacku na subscribe jesteś w fazie trawienia, w funkcji objętej Dispatcherem, więc wszystko co używa dispatchera będzie zdeferowane. To nie jest tragedia, ale łatwiej pisze się testy, jeżeli test nie jest w kolejce Dispatchera. Dodatkowo, jakby coś poszło nie tak, to zobaczyłbyś błąd w następnym teście, a nie tym, co też jest cięższe do ogarnięcia.
Tłumaczę, bo to już bebechy i Jasmine i Immview, więc niełatwo byłoby pewnie do tego dojść.

2017-01-04 23:44 UTC, arturkulig commented on src/Observable.spec.ts
> +        const tester = value => {
[optional] można inline'ować j.w.

2017-01-04 23:44 UTC, arturkulig commented on src/Observable.spec.ts
> +            tester(value)
[must] reduce powinien wyemitować trzy wartości. W tym przypadku: 1, 3, 6

2017-01-04 23:44 UTC, arturkulig commented on src/Observable.spec.ts
> +        const subscription = new Observable(observer => {
[optional] tutaj wlasciwie tez moglbys uzyc Observable::of

2017-01-04 23:46 UTC, arturkulig commented
:balloon:

2017-01-05 08:25 UTC, sebryu commented on src/Observable.spec.ts
> +            setTimeout(done)
No oki, wzorowałem się na testach z BaseObservable, i wymyśliłem że to jest istotne 👍

2017-01-05 08:28 UTC, sebryu commented on src/Observable.spec.ts
> +            tester(value)
Ok, wzorowałem się na tym https://github.com/zenparsing/zen-observable#observablereduce--callback--initialvalue-

Zmienię tak żeby każdą wartość przetwarzało osobno :+1:

2017-01-05 08:31 UTC, sebryu commented on src/Observable.spec.ts
> +        const subscription = new Observable(observer => {
@arturkulig  Pewnie tak. Chciałem mieć sprawdzanie wartości po każdym wykonaniu, a nie wiem jak to zrealizować z `Observable.of`? Czy tak jak w BaseObservable.spec zrobić coś w stylu firstValueTester / secondValueTester / thirdValueTester? Czy można jakoś prościej?

2017-01-05 19:11 UTC, arturkulig requested changes
proponuje, żebyś tylko poprawił to co jest i odbijał do mnie

2017-01-05 19:11 UTC, arturkulig commented on src/Observable.ts
> +            this.subscribe(
jest połączenie zakończenia strumienia pochodnego w razie zakonczenia strumienia źródłowego

ale nie ma połączenia anulowania subskrypcji w razie żądania zakończenia strumienia pochodnego

::subscribe zwraca obiekt subskrypcji, który ma metodę unsubscribe.
funkcja podana w constructor Observable'a może zwrócić funkcję, która będzie uruchomiona, jeżeli skądś przyjdzie żądanie zakończenia tego nowego strumienia.

funkcja podana w constructor Observable'a powinna zwracać funkcję, która wywoła to unsubscribe

2017-01-05 19:11 UTC, arturkulig commented on src/Observable.spec.ts
> +        const subscription = Observable.of(1, 2, 3).map(
opcjonalne - staraj się zaczynać wiersz od kropki

2017-01-05 19:11 UTC, arturkulig commented on src/Observable.ts
> +            let _summary : U = null
nie ma nigdzie `summary`, zmienna nie wyjdzie poza tą funkcję, więc `_` jest zbędne :P

2017-01-05 19:11 UTC, arturkulig commented on src/Observable.ts
> +                            return undefined
return undefined -> return

2017-01-05 19:11 UTC, arturkulig commented on src/Observable.ts
> +                        return observer.error(e)
niby zadziała, ale zmyłka - observer.error nic nie zwróci, więc bardziej czytelne będzie

observer.error
return

2017-01-05 19:11 UTC, arturkulig commented on src/Observable.ts
> +                        newValue = action(value)
możesz spokojnie napisać observer.next(action(value))
jak action rzuci błędem, next nie będzie wołane

2017-01-05 19:12 UTC, arturkulig commented
:goal_net:

2017-01-05 21:56 UTC, sebryu commented on src/Observable.spec.ts
> +        const subscription = Observable.of(1, 2, 3).map(
Jak rozumiem to chodzi Ci o taki zapis?
```
const subscription = Observable.of(1, 2, 3)
    .map(...)
```

Czy raczej o drugą część?
```
    v => v * 5
)
    .subscribe(...)
```

Rozumiem że to opcjonalne, ale chciałbym ujednolicić styl pisania z twoim :+1:

2017-01-05 21:56 UTC, sebryu commented on src/Observable.ts
> +                        return observer.error(e)
Jak w try użyje `observer.next(action(value))` a tutaj `observer.error(e)` to rozumiem że mogę sobie odpuscić `returna` :)

2017-01-05 21:56 UTC, sebryu commented on src/Observable.ts
> +            let _summary : U = null
Noo... ok 💃

2017-01-05 21:56 UTC, sebryu commented on src/Observable.ts
> +            this.subscribe(
`::subscribe zwraca obiekt subskrypcji, który ma metodę unsubscribe.` o tym wiedziałem :D

ale reszta informacji przydatna. No i zrozumiałem (mam nadzieję) co mam dodać :D

2017-01-05 22:08 UTC, arturkulig commented on src/Observable.spec.ts
> +        const subscription = Observable.of(1, 2, 3).map(
i jeden i drugi jest ok

rozstrzelanie na wiele linii ma jednak sens tylko wtedy kiedy bez tego sa za dlugie

2017-01-05 22:15 UTC, arturkulig commented on src/Observable.ts
> +                        return observer.error(e)
...w konsekwencji - tak

2017-01-05 22:23 UTC, sebryu commented
Ok, w takim razie odbijam ⚽️

2017-01-05 22:29 UTC, arturkulig approved these changes

2017-01-05 22:30 UTC, merged

2017-01-05 22:30 UTC, arturkulig commented
:tada: