added scan implementation and specs to observable
arturkulig/immview pull request #2
Opened 2017-01-06 19:51 UTC by sebryu

2017-01-06 22:43 UTC, arturkulig requested changes
poczytałem testy RxJS i oni uzywaja troche inaczej nazw.
nie ma co wyważać drzwi - ktos juz te rzeczy nazwał

zmien nazwe reduce na scan
i scan nazwij bufferCount

zobacz tutaj - https://github.com/ReactiveX/rxjs/blob/master/spec/operators/bufferCount-spec.ts
pierwszy test ilustruje najlepiej o co chodzi.

wtedy obecne scan(x) to będzie bufferCount(x, 1)

więcej możliwości.

2017-01-06 22:43 UTC, arturkulig commented on src/Observable.spec.ts
> +        const expectedValues = [[1, 0, 0], [2, 1, 0], [3, 2, 1]]
tak tylko odwrotnie [[0, 0, 1], [0, 1, 2], [1, 2, 3]]

2017-01-06 22:43 UTC, arturkulig commented on src/Observable.ts
> +            ? Array(historyLength).fill(defaultValue)
nie ma lekko -> https://developer.mozilla.org/pl/docs/Web/JavaScript/Referencje/Obiekty/Array/fill#Kompatybilność_z_przeglądarkami

2017-01-06 22:43 UTC, arturkulig commented on src/Observable.ts
> +                    if (observer.closed) {
teraz do mnie dopiero doszło.

ten warunek miał strzec subskrypcje zeby nie działały jak node został wyłączony.

w momencie kiedy zwracamy funkcje wyrejestrowującą ze wszelkich triggerów, to jest to zbędne

2017-01-06 23:05 UTC, sebryu commented on src/Observable.ts
> +                    if (observer.closed) {
Ok, jak rozumiem to we wszystkich napisanych przeze mnie funkcjach usunąć ten warunek?

2017-01-06 23:06 UTC, sebryu commented on src/Observable.ts
> +            ? Array(historyLength).fill(defaultValue)
: < ok 😞

2017-01-06 23:08 UTC, sebryu commented on src/Observable.spec.ts
> +        const expectedValues = [[1, 0, 0], [2, 1, 0], [3, 2, 1]]
Zastanawiałem się nad tym, i stwierdziłem że fajnie będzie, jak pierwszym elementem będzie najnowsza wiadomość. Czy zwracanie najnowszej wiadomości jako ostatniej jest czymś podyktowane? (Znaczy i tak zmienie, ale mnie ciekawi czemu tak)

2017-01-07 00:17 UTC, arturkulig commented on src/Observable.spec.ts
> +        const expectedValues = [[1, 0, 0], [2, 1, 0], [3, 2, 1]]
Kiedy nowa wartość pojawia się w strumieniu to jest następna po poprzedniej - to brzmi idiotycznie, ale tak należy to sobie wyobrazić. To wynik tego, że strumień to sekwencja tylko rozciągnięta w czasie.
Taki "scan" to operacja utrzymywania sekwencji (już nie rozciągniętej w czasie) wszystkich wartości jakie do tej pory się pojawiły i wybieranie ostatnich `x`.

Wartości w odwrotnej kolejności wymagałyby jeszcze jednej operacji odwrócenia sekwencji.

Jak ten argument Cię nie przekonuje to są jeszcze dwa inne:

Jak patrzysz na taką tablicę to masz wartości uporządkowane względem czasu w naturalnym kierunku czytania.

Ostatecznie: tak właśnie było w wersji pierwszej

2017-01-07 00:19 UTC, arturkulig commented on src/Observable.ts
> +                    if (observer.closed) {
Tak

2017-01-07 12:58 UTC, sebryu commented on src/Observable.spec.ts
> +        const expectedValues = [[1, 0, 0], [2, 1, 0], [3, 2, 1]]
Argument wystarczający : ) W sumie wszystkie trzy bym zaakceptował

2017-01-07 20:24 UTC, sebryu commented
Zastosowałem uwagi, podmieniłem nazwy, i podpatrzyłem parę testów z rxjs.

Istotna zmiana - Observable.from będzie teraz wołało complete(), jak przeiteruje przez wszystkie wartości (było mi to potrzebne dla sytuacji w której bufor miał jakieś wiadomości, a ich nie wypluwał bo jeszcze nie miał odpowiedniego rozmiaru.

2017-01-07 23:25 UTC, arturkulig approved these changes
zobacz te notatki i możesz merge'ować

bardzo ładne testy!

2017-01-07 23:25 UTC, arturkulig commented on src/Observable.ts
> +            return new Observable<T>(({next, error, complete}) => {
używaj proszę observer.next() zamiast destrukturyzowania obiektu observera, bo co prawda nasza implementacja ma zafiksowany kontekst, to jeżeli coś będzie używać `this` w tym next, to nie zadziała, bo wywołujesz funkcję bez kontekstu. #justJavaScriptThings

2017-01-07 23:25 UTC, arturkulig commented on src/Observable.ts
> +    bufferCount(bufferSize: number, startBufferEvery: number = null): Observable<T[]> {
startBufferEvery -> customBufferInteval ?

2017-01-07 23:25 UTC, arturkulig commented on src/Observable.ts
> +                    history.unshift(value)
jak zamienisz unshift na push, to nie bedziesz nizej musial robic reversa

2017-01-07 23:25 UTC, arturkulig commented on src/Observable.ts
> +                    if (newMessage) {
if (history.length > bufferSize - bufferInterval) {

2017-01-08 13:58 UTC, arturkulig commented on src/Observable.ts
> +            return new Observable<T>(({next, error, complete}) => {
w sumie głupoty pisze - tutaj ewidentnie tworzysz observable z immview, wiec przejdzie.

niemniej byłoby czytelniej trzymać to jednym stylu

2017-01-10 10:13 UTC, arturkulig commented
@sebryu poprawiłem :+1:

2017-01-10 10:14 UTC, merged

2017-01-12 15:03 UTC, sebryu commented
Przeczytałem sobie twój commit. Ładny 👍